abstract class MyCloudFunctionsErrorCodes {
  static const ERROR_INTERNAL = 'ERROR_INTERNAL';
  static const ERROR_NOT_AUTHENTICATED = 'ERROR_NOT_AUTHENTICATED';
  static const ERROR_USER_NOT_FOUND = 'ERROR_USER_NOT_FOUND';
  static const ERROR_RECEIVER_ALREADY_HAS_PARTNER =
      'ERROR_RECEIVER_ALREADY_HAS_PARTNER';
  static const ERROR_RECEIVER_HAS_PENDING_REQUEST =
      'ERROR_RECEIVER_HAS_PENDING_REQUEST';
  static const ERROR_RECEIVER_EMAIL_REQUIRED = 'ERROR_RECEIVER_EMAIL_REQUIRED';
  static const ERROR_RECEIVER_EMAIL_IS_SENDERS = 'ERROR_RECEIVER_EMAIL_IS_SENDERS';
}